// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltraMonkeyEFLibrary;

#nullable disable

namespace UltraMonkeyEFLibrary.Migrations
{
    [DbContext(typeof(UltraMonkeyContext))]
    [Migration("20220221201603_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UltraMonkeyEFLibrary.WeatherData", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.Property<int?>("AirMoisture")
                        .HasColumnType("int");

                    b.Property<double>("Diff")
                        .HasColumnType("float");

                    b.Property<int?>("MoldIndex")
                        .HasColumnType("int");

                    b.Property<double?>("OpenTime")
                        .HasColumnType("float");

                    b.Property<float>("Temp")
                        .HasColumnType("real");

                    b.HasKey("Date", "Location");

                    b.ToTable("WeatherDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
